import Link from 'next/link'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import ExperiencesCard from '../components/experiencesCard'
import Footer from '../components/footer/footer'

export default function Home() {
    return (
        // <div className={styles.container}>
        <>
            <Head>
                <title>Airbnb Clone</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <>
                {/* <div className={styles['main']}> */}
                <div className={styles['search--container']}>
                    <button className={styles['search--button']}>
                        <svg
                            viewBox="0 0 32 32"
                            xmlns="http://www.w3.org/2000/svg"
                            aria-hidden="true"
                            role="presentation"
                            focusable="false"
                            className={styles['search--button-logo']}
                        >
                            <g fill="none">
                                <path d="m13 24c6.0751322 0 11-4.9248678 11-11 0-6.07513225-4.9248678-11-11-11-6.07513225 0-11 4.92486775-11 11 0 6.0751322 4.92486775 11 11 11zm8-3 9 9"></path>
                            </g>
                        </svg>
                        <p className={styles['search--button-caption']}>
                            Where are you going?
                        </p>
                    </button>
                </div>
                <div className={styles['ukraine--container']}>
                    <div className={styles['ukraine--text']}>
                        <h1 className={styles['ukraine--text-title']}>
                            Help house <br />
                            100,000 refugees <br />
                            fleeing Ukraine
                        </h1>
                        <Link href="#">
                            <a className={styles['ukraine--text-link']}>
                                Learn more
                            </a>
                        </Link>
                    </div>
                </div>

                <div className={styles['cabin--container']}>
                    <div className={styles['cabin--card']}>
                        <h2 className={styles['cabin--card-title']}>
                            Let your curiosity do <br /> the booking
                        </h2>
                        <Link href="#">
                            <a className={styles['cabin--card-link']}>
                                <span
                                    className={styles['cabin--card-link_text']}
                                >
                                    I{`'`}m flexible
                                </span>
                            </a>
                        </Link>
                    </div>
                </div>
                {/* </div> */}

                <h2 className={styles['discover--title']}>
                    Discover Airbnb <br />
                    Experiences
                </h2>

                <div className={styles['experiences-cards--container']}>
                    <ExperiencesCard
                        title={'Things to do on your trip'}
                        linkText={'Experiences'}
                        imageUrl={'/images/cave-exploring-cropped.svg'}
                        imageAlt={'person exploring cave'}
                    />

                    <ExperiencesCard
                        title={'Things to do from home'}
                        linkText={'Online Experiences'}
                        imageUrl={'/images/woman-cooking-cropped.svg'}
                        imageAlt={'woman cooking'}
                    />
                </div>

                <div className={styles['gift-cards--container']}>
                    <h2 className={styles['gift-cards--title']}>
                        Shop Airbnb gift cards
                    </h2>
                    <Link href="#">
                        <a className={styles['gift-cards--link']}>Learn more</a>
                    </Link>
                    <div className={styles['gift-cards-image_container']}>
                        <Image
                            src="/images/gift-cards.svg"
                            alt="airbnb gift cards"
                            layout="responsive"
                            width={330}
                            height={243.38}
                        />
                    </div>
                </div>

                <div className={styles['hosting--container']}>
                    <h2 className={styles['hosting--title']}>
                        Questions <br /> about <br /> hosting?
                    </h2>
                    <Link href="#">
                        <a className={styles['hosting--link']}>
                            Ask a Superhost
                        </a>
                    </Link>
                </div>

                <Footer />
            </>
        </>
        // </div>
    )
}
